# Generated by Django 4.0.2 on 2022-02-19 11:56

import bank.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[(bank.models.InvestmentType['FD'], 'Fixed Deposit'), (bank.models.InvestmentType['CD'], 'Classic Deposit')], max_length=5)),
                ('investment_status', models.CharField(choices=[(bank.models.DepositType['TENURE'], 'ontenure'), (bank.models.DepositType['WITHDRAWN'], 'withdrawn'), (bank.models.DepositType['BROKEN'], 'broken'), (bank.models.DepositType['FAILURE'], 'failure')], max_length=255)),
                ('principle_amount', models.PositiveIntegerField()),
                ('current_amount', models.PositiveIntegerField()),
                ('startingInterest', models.FloatField()),
                ('tenure', models.PositiveIntegerField(default=0)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
