# Generated by Django 4.0.2 on 2022-02-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_bank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankledger',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='bank.bank'),
        ),
    ]
