# Generated by Django 3.1.8 on 2022-02-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bank_balance_alter_bankledger_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='user',
        ),
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankledger',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BankAccountType',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserBankAccount',
        ),
    ]
