# Generated by Django 4.0.2 on 2022-02-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_cryptowallet_id'),
        ('crypto', '0002_auto_20220220_0513'),
    ]

    operations = [
    ]
