# Generated by Django 4.0.2 on 2022-02-19 20:41

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stocks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StocksWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stocksbalance')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StocksWalletLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[(stocks.models.ActionType['BUY'], 'buy'), (stocks.models.ActionType['SELL'], 'sell')], max_length=5)),
                ('targetStock', models.CharField(max_length=5)),
                ('pricePerStock', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stockwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='stocks.stockswallet')),
            ],
        ),
    ]
